import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, Check, Radio, RefreshCw, UsersRound } from 'lucide-react';
import { apiClient } from '../api/client';
import WorkspaceHeader from '../components/WorkspaceHeader';
import ResqMap from '../components/ResqMap';
import StatusPill from '../components/StatusPill';
import useRealtime from '../hooks/useRealtime';
import './AdminControlCenter.css';

const nextStatuses = ['dispatched', 'en_route', 'arrived', 'resolved'];

export default function AdminControlCenter() {
  const [dashboard, setDashboard] = useState(null); const [incidents, setIncidents] = useState([]); const [responders, setResponders] = useState([]); const [selectedNumber, setSelectedNumber] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [metrics, nextIncidents, nextResponders] = await Promise.all([apiClient.adminDashboard(), apiClient.adminIncidents(), apiClient.adminResponders()]); setDashboard(metrics); setIncidents(nextIncidents); setResponders(nextResponders); setSelectedNumber((current) => current || nextIncidents[0]?.number || null); } catch (reason) { setError(reason.message); } }, []);
  useEffect(() => { load(); }, [load]); const live = useRealtime(load); const selected = incidents.find((item) => item.number === selectedNumber) || null;
  const markers = useMemo(() => [
    ...incidents.filter((item) => item.status !== 'resolved').map((item) => ({ id: item.id, title: `${item.id} — ${item.category.label}`, position: { lat: item.location.lat, lng: item.location.lng }, kind: item.severity, label: '!' })),
    ...responders.filter((unit) => unit.location).map((unit) => ({ id: `unit-${unit.id}`, title: `${unit.name} · ${unit.service}`, position: { lat: unit.location.lat, lng: unit.location.lng }, kind: 'responder', label: 'R' })),
  ], [incidents, responders]);
  async function updateStatus(status) { if (!selected) return; setBusy(true); try { await apiClient.updateAdminIncident(selected.number, status); await load(); } catch (reason) { setError(reason.message); } finally { setBusy(false); } }
  const critical = incidents.filter((item) => item.severity === 'critical' && item.status !== 'resolved').length;
  return <div className="admin-console"><WorkspaceHeader dark title="Emergency Command Center" backTo="/admin/control-center" actions={<span className={`live-indicator ${live ? 'on' : ''}`}><i/> {live ? 'REALTIME' : 'CONNECTING'}</span>}/><main className="admin-console__main">
    <section className="admin-console__stats"><Metric label="ACTIVE INCIDENTS" value={dashboard?.active ?? '—'} icon={<Activity size={16}/>}/><Metric label="CRITICAL" value={dashboard?.critical ?? critical} icon={<Radio size={16}/>}/><Metric label="RESPONDERS" value={dashboard?.responders ?? '—'} icon={<UsersRound size={16}/>}/><Metric label="CITIZENS" value={dashboard?.citizens ?? '—'} icon={<BarChart3 size={16}/>}/><button className="admin-console__refresh" onClick={load}><RefreshCw size={15}/> Refresh data</button></section>
    {error && <p className="workspace-error">{error}</p>}
    <section className="admin-console__layout"><aside className="admin-queue"><div className="admin-queue__head"><div><p>INCIDENT QUEUE</p><h2>{incidents.length} total</h2></div><span>Admin view</span></div><div className="admin-queue__filters"><span>All active and resolved incidents from MongoDB</span></div><div className="admin-queue__list">{incidents.map((item) => <button key={item.id} onClick={() => setSelectedNumber(item.number)} className={`${selectedNumber === item.number ? 'selected ' : ''}${item.severity}`}><div><span>{item.id}</span><StatusPill value={item.severity}/></div><h3>{item.category.icon} {item.category.label}</h3><p>{item.text}</p><footer><StatusPill value={item.status}/><small>{item.assignedResponders.length} assigned</small></footer></button>)}</div></aside><section className="admin-map"><ResqMap markers={markers} onMarkerClick={(marker) => marker.id.startsWith('INC-') && setSelectedNumber(Number(marker.id.replace('INC-', '')))}/><div className="admin-map__layers"><p>MAP LAYERS</p><span><i className="danger"/> Incidents</span><span><i className="unit"/> Responders</span><span><i className="live"/> Browser GPS only</span></div></section><aside className="admin-detail">{selected ? <AdminDetail incident={selected} busy={busy} onUpdate={updateStatus}/> : <p className="admin-detail__empty">Select an incident to inspect it.</p>}</aside></section>
    <section className="admin-analytics"><div><p>NETWORK OVERVIEW</p><h2>Incident patterns</h2></div><div className="admin-analytics__group">{dashboard?.byCategory?.length ? dashboard.byCategory.map((item) => <span key={item._id}><b>{item.count}</b>{item._id}</span>) : <span>No reports yet</span>}</div><div className="admin-analytics__hotspots"><h3>Most reported locations</h3>{dashboard?.hotspots?.length ? dashboard.hotspots.map((spot) => <p key={spot._id}><span>{spot._id}</span><b>{spot.incidents} reports</b></p>) : <p>No location data yet.</p>}</div></section>
  </main></div>;
}

function Metric({ label, value, icon }) { return <div className="admin-metric"><span>{icon}{label}</span><strong>{value}</strong></div>; }
function AdminDetail({ incident, busy, onUpdate }) { return <><div className="admin-detail__meta"><span>{incident.id}</span><StatusPill value={incident.status}/></div><h2>{incident.category.icon} {incident.category.label}</h2><p className="admin-detail__description">{incident.text}</p><div className="admin-detail__line"><span>Severity</span><StatusPill value={incident.severity}/></div><div className="admin-detail__line"><span>Confidence</span><b>{incident.confidence}%</b></div><div className="admin-detail__line"><span>Reports grouped</span><b>{incident.reportCount}</b></div><section><p>LOCATION</p><strong>{incident.location.label}</strong></section><section><p>ASSIGNED RESPONDERS</p>{incident.assignedResponders.length ? incident.assignedResponders.map((unit) => <div className="admin-detail__unit" key={unit.id}><span>{unit.name}<small>{unit.service} · {unit.code}</small></span><StatusPill value={unit.availability}/></div>) : <em>Awaiting responder acceptance</em>}</section><section><p>RECOMMENDED ACTION</p><div className="admin-detail__recommendation">{incident.recommendedAction}</div></section>{incident.status !== 'resolved' && <div className="admin-detail__controls">{nextStatuses.filter((status) => status !== incident.status).map((status) => <button key={status} disabled={busy} onClick={() => onUpdate(status)}>{status === 'resolved' && <Check size={14}/>}{status.replace('_', ' ')}</button>)}</div>}</>;
}
